{% load_yaml as rawmap %}
CentOS:
    server_package: mariadb-server
    client_package: mariadb
    pymysql: MySQL-python
    service: mariadb
    admin: True
    config:
        file: /etc/my.cnf
        sections:
            mysqld:
                bind-address: 0.0.0.0
                port: 3306
    master_user:
        username: root
        password: root
{% endload %}
